export const COMPANY_USER_REQUEST = 'COMPANY_USER_REQUEST'
export const COMPANY_REQUEST = 'COMPANY_REQUEST'
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS'
export const COMPANY_ERROR = 'COMPANY_ERROR'
